name: gapless_audio_loop_example
description: Demonstrates how to use the gapless_audio_loop plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  gapless_audio_loop:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/Loop-Menu.wav
